services:
  db:
    image: postgres:13.1-alpine
    hostname: ${POSTGRES_HOSTNAME:-db}
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: deployment_manager
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-aaaa}
  web:
    build: .
    networks:
      - reverse_proxy
      - default
    depends_on:
      - db
    environment:
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY:-aaaa}
      POSTGRES_HOSTNAME: ${POSTGRES_HOSTNAME:-db}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-aaaa}
      DOMAIN: ${DOMAIN:-aaaa}
      RAILS_ENV: production
      RAILS_SERVE_STATIC_FILES: 'true'
      RAILS_LOG_TO_STDOUT: 'true'
    labels:
      - traefik.enable=true
      - traefik.docker.network=reverse_proxy
      - traefik.http.routers.${ROUTER_NAME:-deployment_manager}.rule=Host(`${DOMAIN:-aaaa}`)
      - traefik.http.routers.${ROUTER_NAME:-deployment_manager}.tls.certresolver=letsencrypt
volumes:
  db-data:
networks:
  reverse_proxy:
    name: reverse_proxy